"""initial schema

Revision ID: 0ed68617b946
Revises: 
Create Date: 2026-09-17 12:04:10.681767

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '0ed68617b946'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('repositories',
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('source_type', sa.Enum('GITHUB', 'ZIP', name='repository_source_type'), nullable=False),
    sa.Column('source_url', sa.String(length=1024), nullable=True),
    sa.Column('local_path', sa.String(length=1024), nullable=True),
    sa.Column('default_branch', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'CLONING', 'SCANNING', 'PARSING', 'EMBEDDING', 'SUMMARIZING', 'READY', 'FAILED', name='repository_status'), nullable=False),
    sa.Column('status_detail', sa.String(length=500), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('languages', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('frameworks', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('summary', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('file_count', sa.Integer(), nullable=False),
    sa.Column('total_size_bytes', sa.Integer(), nullable=False),
    sa.Column('last_indexed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_repositories_owner_id'), 'repositories', ['owner_id'], unique=False)
    op.create_index(op.f('ix_repositories_status'), 'repositories', ['status'], unique=False)
    op.create_table('conversations',
    sa.Column('repository_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversations_repository_id'), 'conversations', ['repository_id'], unique=False)
    op.create_index(op.f('ix_conversations_user_id'), 'conversations', ['user_id'], unique=False)
    op.create_table('repository_files',
    sa.Column('repository_id', sa.UUID(), nullable=False),
    sa.Column('path', sa.String(length=1024), nullable=False),
    sa.Column('language', sa.String(length=64), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('line_count', sa.Integer(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('is_test', sa.Boolean(), nullable=False),
    sa.Column('is_config', sa.Boolean(), nullable=False),
    sa.Column('is_documentation', sa.Boolean(), nullable=False),
    sa.Column('is_binary', sa.Boolean(), nullable=False),
    sa.Column('skipped_reason', sa.String(length=255), nullable=True),
    sa.Column('parse_error', sa.String(length=1024), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('repository_id', 'path', name='uq_repo_file_path')
    )
    op.create_index(op.f('ix_repository_files_language'), 'repository_files', ['language'], unique=False)
    op.create_index(op.f('ix_repository_files_path'), 'repository_files', ['path'], unique=False)
    op.create_index(op.f('ix_repository_files_repository_id'), 'repository_files', ['repository_id'], unique=False)
    op.create_table('messages',
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.Enum('USER', 'ASSISTANT', 'SYSTEM', name='message_role'), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('citations', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('token_usage', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_messages_conversation_id'), 'messages', ['conversation_id'], unique=False)
    op.create_table('repository_symbols',
    sa.Column('repository_id', sa.UUID(), nullable=False),
    sa.Column('file_id', sa.UUID(), nullable=False),
    sa.Column('parent_symbol_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=512), nullable=False),
    sa.Column('symbol_type', sa.String(length=32), nullable=False),
    sa.Column('language', sa.String(length=64), nullable=False),
    sa.Column('start_line', sa.Integer(), nullable=False),
    sa.Column('end_line', sa.Integer(), nullable=False),
    sa.Column('signature', sa.Text(), nullable=True),
    sa.Column('docstring', sa.Text(), nullable=True),
    sa.Column('route_path', sa.String(length=512), nullable=True),
    sa.Column('http_method', sa.String(length=16), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['repository_files.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_symbol_id'], ['repository_symbols.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_repository_symbols_file_id'), 'repository_symbols', ['file_id'], unique=False)
    op.create_index(op.f('ix_repository_symbols_name'), 'repository_symbols', ['name'], unique=False)
    op.create_index(op.f('ix_repository_symbols_repository_id'), 'repository_symbols', ['repository_id'], unique=False)
    op.create_index(op.f('ix_repository_symbols_symbol_type'), 'repository_symbols', ['symbol_type'], unique=False)
    op.create_table('tasks',
    sa.Column('repository_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('task_type', sa.Enum('CHAT', 'DEBUG', 'FEATURE', 'SECURITY_SCAN', 'GENERAL', name='task_type'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'IN_PROGRESS', 'COMPLETED', 'FAILED', 'BLOCKED', name='task_status'), nullable=False),
    sa.Column('root_cause', sa.Text(), nullable=True),
    sa.Column('evidence', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('evidence_status', sa.Enum('OBSERVED', 'INFERRED', 'HYPOTHESIZED', 'VERIFIED', 'INSUFFICIENT', name='evidence_status'), nullable=True),
    sa.Column('confidence_notes', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tasks_repository_id'), 'tasks', ['repository_id'], unique=False)
    op.create_index(op.f('ix_tasks_status'), 'tasks', ['status'], unique=False)
    op.create_index(op.f('ix_tasks_user_id'), 'tasks', ['user_id'], unique=False)
    op.create_table('agent_runs',
    sa.Column('repository_id', sa.UUID(), nullable=False),
    sa.Column('task_id', sa.UUID(), nullable=True),
    sa.Column('agent_name', sa.Enum('ORCHESTRATOR', 'PLANNER', 'REPOSITORY', 'DEBUGGER', 'SECURITY', 'TEST', 'FIX', 'REVIEW', 'VALIDATION', name='agent_name'), nullable=False),
    sa.Column('status', sa.Enum('RUNNING', 'COMPLETED', 'FAILED', 'CANCELLED', name='agent_run_status'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('input_summary', sa.Text(), nullable=True),
    sa.Column('output_summary', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('files_accessed', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('files_modified', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('model', sa.String(length=128), nullable=True),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('total_tokens', sa.Integer(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_runs_agent_name'), 'agent_runs', ['agent_name'], unique=False)
    op.create_index(op.f('ix_agent_runs_repository_id'), 'agent_runs', ['repository_id'], unique=False)
    op.create_index(op.f('ix_agent_runs_status'), 'agent_runs', ['status'], unique=False)
    op.create_index(op.f('ix_agent_runs_task_id'), 'agent_runs', ['task_id'], unique=False)
    op.create_table('approvals',
    sa.Column('repository_id', sa.UUID(), nullable=False),
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('approval_type', sa.Enum('CODE_CHANGE', 'GIT_OPERATION', 'PR_CREATION', name='approval_type'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'CHANGES_REQUESTED', name='approval_status'), nullable=False),
    sa.Column('summary_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_approvals_repository_id'), 'approvals', ['repository_id'], unique=False)
    op.create_index(op.f('ix_approvals_status'), 'approvals', ['status'], unique=False)
    op.create_index(op.f('ix_approvals_task_id'), 'approvals', ['task_id'], unique=False)
    op.create_table('pull_requests',
    sa.Column('repository_id', sa.UUID(), nullable=False),
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('branch_name', sa.String(length=255), nullable=False),
    sa.Column('base_branch', sa.String(length=255), nullable=False),
    sa.Column('commit_sha', sa.String(length=64), nullable=True),
    sa.Column('pr_number', sa.Integer(), nullable=True),
    sa.Column('pr_url', sa.String(length=1024), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'BRANCH_CREATED', 'COMMITTED', 'PUSHED', 'PR_CREATED', 'FAILED', name='pull_request_status'), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pull_requests_repository_id'), 'pull_requests', ['repository_id'], unique=False)
    op.create_index(op.f('ix_pull_requests_status'), 'pull_requests', ['status'], unique=False)
    op.create_index(op.f('ix_pull_requests_task_id'), 'pull_requests', ['task_id'], unique=False)
    op.create_table('repository_dependencies',
    sa.Column('repository_id', sa.UUID(), nullable=False),
    sa.Column('relationship_type', sa.Enum('IMPORTS', 'CALLS', 'INHERITS', 'IMPLEMENTS', 'USES', 'DEPENDS_ON', 'EXPOSES', 'READS_FROM', 'WRITES_TO', name='dependency_relationship_type'), nullable=False),
    sa.Column('source_file_id', sa.UUID(), nullable=False),
    sa.Column('source_symbol_id', sa.UUID(), nullable=True),
    sa.Column('target_file_id', sa.UUID(), nullable=True),
    sa.Column('target_symbol_id', sa.UUID(), nullable=True),
    sa.Column('raw_reference', sa.String(length=1024), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_file_id'], ['repository_files.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_symbol_id'], ['repository_symbols.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_file_id'], ['repository_files.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_symbol_id'], ['repository_symbols.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_repository_dependencies_relationship_type'), 'repository_dependencies', ['relationship_type'], unique=False)
    op.create_index(op.f('ix_repository_dependencies_repository_id'), 'repository_dependencies', ['repository_id'], unique=False)
    op.create_index(op.f('ix_repository_dependencies_source_file_id'), 'repository_dependencies', ['source_file_id'], unique=False)
    op.create_index(op.f('ix_repository_dependencies_target_file_id'), 'repository_dependencies', ['target_file_id'], unique=False)
    op.create_table('task_steps',
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('step_number', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'IN_PROGRESS', 'COMPLETED', 'FAILED', 'BLOCKED', name='task_step_status'), nullable=False),
    sa.Column('evidence', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_steps_task_id'), 'task_steps', ['task_id'], unique=False)
    op.create_table('code_changes',
    sa.Column('repository_id', sa.UUID(), nullable=False),
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('agent_run_id', sa.UUID(), nullable=True),
    sa.Column('change_type', sa.Enum('CREATE', 'MODIFY', 'DELETE', name='change_type'), nullable=False),
    sa.Column('lifecycle_state', sa.Enum('PROPOSED', 'APPLIED', 'TESTED', 'VALIDATED', 'REJECTED', name='change_lifecycle_state'), nullable=False),
    sa.Column('file_path', sa.String(length=1024), nullable=False),
    sa.Column('old_content', sa.Text(), nullable=True),
    sa.Column('new_content', sa.Text(), nullable=True),
    sa.Column('diff', sa.Text(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('agent_name', sa.String(length=64), nullable=False),
    sa.Column('workspace_id', sa.String(length=128), nullable=False),
    sa.Column('applied_to_main', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agent_run_id'], ['agent_runs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_code_changes_lifecycle_state'), 'code_changes', ['lifecycle_state'], unique=False)
    op.create_index(op.f('ix_code_changes_repository_id'), 'code_changes', ['repository_id'], unique=False)
    op.create_index(op.f('ix_code_changes_task_id'), 'code_changes', ['task_id'], unique=False)
    op.create_table('findings',
    sa.Column('repository_id', sa.UUID(), nullable=False),
    sa.Column('task_id', sa.UUID(), nullable=True),
    sa.Column('agent_run_id', sa.UUID(), nullable=True),
    sa.Column('finding_type', sa.String(length=128), nullable=False),
    sa.Column('severity', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='finding_severity'), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'ACKNOWLEDGED', 'RESOLVED', 'FALSE_POSITIVE', name='finding_status'), nullable=False),
    sa.Column('file_path', sa.String(length=1024), nullable=False),
    sa.Column('start_line', sa.Integer(), nullable=True),
    sa.Column('end_line', sa.Integer(), nullable=True),
    sa.Column('evidence', sa.Text(), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.Column('impact', sa.Text(), nullable=True),
    sa.Column('remediation', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agent_run_id'], ['agent_runs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_findings_finding_type'), 'findings', ['finding_type'], unique=False)
    op.create_index(op.f('ix_findings_repository_id'), 'findings', ['repository_id'], unique=False)
    op.create_index(op.f('ix_findings_severity'), 'findings', ['severity'], unique=False)
    op.create_index(op.f('ix_findings_status'), 'findings', ['status'], unique=False)
    op.create_table('test_runs',
    sa.Column('repository_id', sa.UUID(), nullable=False),
    sa.Column('task_id', sa.UUID(), nullable=True),
    sa.Column('agent_run_id', sa.UUID(), nullable=True),
    sa.Column('framework', sa.String(length=64), nullable=True),
    sa.Column('command', sa.String(length=1024), nullable=False),
    sa.Column('exit_code', sa.Integer(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('passed_count', sa.Integer(), nullable=True),
    sa.Column('failed_count', sa.Integer(), nullable=True),
    sa.Column('output', sa.Text(), nullable=True),
    sa.Column('error_output', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('PASSED', 'FAILED', 'ERROR', 'TIMEOUT', name='test_run_status'), nullable=False),
    sa.Column('iteration', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agent_run_id'], ['agent_runs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_test_runs_repository_id'), 'test_runs', ['repository_id'], unique=False)
    op.create_index(op.f('ix_test_runs_status'), 'test_runs', ['status'], unique=False)
    op.create_index(op.f('ix_test_runs_task_id'), 'test_runs', ['task_id'], unique=False)
    op.create_table('tool_calls',
    sa.Column('agent_run_id', sa.UUID(), nullable=False),
    sa.Column('tool_name', sa.String(length=128), nullable=False),
    sa.Column('arguments', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('result_summary', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agent_run_id'], ['agent_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tool_calls_agent_run_id'), 'tool_calls', ['agent_run_id'], unique=False)
    op.create_index(op.f('ix_tool_calls_tool_name'), 'tool_calls', ['tool_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tool_calls_tool_name'), table_name='tool_calls')
    op.drop_index(op.f('ix_tool_calls_agent_run_id'), table_name='tool_calls')
    op.drop_table('tool_calls')
    op.drop_index(op.f('ix_test_runs_task_id'), table_name='test_runs')
    op.drop_index(op.f('ix_test_runs_status'), table_name='test_runs')
    op.drop_index(op.f('ix_test_runs_repository_id'), table_name='test_runs')
    op.drop_table('test_runs')
    op.drop_index(op.f('ix_findings_status'), table_name='findings')
    op.drop_index(op.f('ix_findings_severity'), table_name='findings')
    op.drop_index(op.f('ix_findings_repository_id'), table_name='findings')
    op.drop_index(op.f('ix_findings_finding_type'), table_name='findings')
    op.drop_table('findings')
    op.drop_index(op.f('ix_code_changes_task_id'), table_name='code_changes')
    op.drop_index(op.f('ix_code_changes_repository_id'), table_name='code_changes')
    op.drop_index(op.f('ix_code_changes_lifecycle_state'), table_name='code_changes')
    op.drop_table('code_changes')
    op.drop_index(op.f('ix_task_steps_task_id'), table_name='task_steps')
    op.drop_table('task_steps')
    op.drop_index(op.f('ix_repository_dependencies_target_file_id'), table_name='repository_dependencies')
    op.drop_index(op.f('ix_repository_dependencies_source_file_id'), table_name='repository_dependencies')
    op.drop_index(op.f('ix_repository_dependencies_repository_id'), table_name='repository_dependencies')
    op.drop_index(op.f('ix_repository_dependencies_relationship_type'), table_name='repository_dependencies')
    op.drop_table('repository_dependencies')
    op.drop_index(op.f('ix_pull_requests_task_id'), table_name='pull_requests')
    op.drop_index(op.f('ix_pull_requests_status'), table_name='pull_requests')
    op.drop_index(op.f('ix_pull_requests_repository_id'), table_name='pull_requests')
    op.drop_table('pull_requests')
    op.drop_index(op.f('ix_approvals_task_id'), table_name='approvals')
    op.drop_index(op.f('ix_approvals_status'), table_name='approvals')
    op.drop_index(op.f('ix_approvals_repository_id'), table_name='approvals')
    op.drop_table('approvals')
    op.drop_index(op.f('ix_agent_runs_task_id'), table_name='agent_runs')
    op.drop_index(op.f('ix_agent_runs_status'), table_name='agent_runs')
    op.drop_index(op.f('ix_agent_runs_repository_id'), table_name='agent_runs')
    op.drop_index(op.f('ix_agent_runs_agent_name'), table_name='agent_runs')
    op.drop_table('agent_runs')
    op.drop_index(op.f('ix_tasks_user_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_status'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_repository_id'), table_name='tasks')
    op.drop_table('tasks')
    op.drop_index(op.f('ix_repository_symbols_symbol_type'), table_name='repository_symbols')
    op.drop_index(op.f('ix_repository_symbols_repository_id'), table_name='repository_symbols')
    op.drop_index(op.f('ix_repository_symbols_name'), table_name='repository_symbols')
    op.drop_index(op.f('ix_repository_symbols_file_id'), table_name='repository_symbols')
    op.drop_table('repository_symbols')
    op.drop_index(op.f('ix_messages_conversation_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_repository_files_repository_id'), table_name='repository_files')
    op.drop_index(op.f('ix_repository_files_path'), table_name='repository_files')
    op.drop_index(op.f('ix_repository_files_language'), table_name='repository_files')
    op.drop_table('repository_files')
    op.drop_index(op.f('ix_conversations_user_id'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_repository_id'), table_name='conversations')
    op.drop_table('conversations')
    op.drop_index(op.f('ix_repositories_status'), table_name='repositories')
    op.drop_index(op.f('ix_repositories_owner_id'), table_name='repositories')
    op.drop_table('repositories')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
