"""add last_security_scan_at to repositories

Revision ID: 8c39bd7a06e9
Revises: 0ed68617b946
Create Date: 2026-09-17 18:35:36.716134

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '8c39bd7a06e9'
down_revision: Union[str, None] = '0ed68617b946'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('repositories', sa.Column('last_security_scan_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('repositories', 'last_security_scan_at')
    # ### end Alembic commands ###
