"""GitHub PR creation (section 34). Only ever called after
approval_type=PR_CREATION has been APPROVED by a human -- see
api/routes/pull_requests.py.
"""
from __future__ import annotations

from dataclasses import dataclass


class GitHubClientError(Exception):
    pass


@dataclass
class CreatedPullRequest:
    number: int
    url: str
    html_url: str


def create_pull_request(
    github_token: str,
    owner: str,
    repo: str,
    branch_name: str,
    base_branch: str,
    title: str,
    body: str,
) -> CreatedPullRequest:
    if not github_token:
        raise GitHubClientError(
            "GITHUB_TOKEN is not configured -- cannot create a pull request via the GitHub API."
        )

    from github import Github, GithubException

    client = Github(github_token)
    try:
        gh_repo = client.get_repo(f"{owner}/{repo}")
        pr = gh_repo.create_pull(title=title, body=body, head=branch_name, base=base_branch)
    except GithubException as exc:
        message = exc.data.get("message", str(exc)) if isinstance(exc.data, dict) else str(exc)
        raise GitHubClientError(f"GitHub PR creation failed: {message}") from exc

    return CreatedPullRequest(number=pr.number, url=pr.url, html_url=pr.html_url)


def build_pr_description(
    problem: str,
    root_cause: str | None,
    changes_summary: str,
    tests_summary: str,
    files_affected: list[str],
) -> str:
    lines = [
        "## Problem",
        problem,
        "",
        "## Root Cause",
        root_cause or "_Not conclusively determined -- see task evidence._",
        "",
        "## Changes",
        changes_summary,
        "",
        "## Files Affected",
        *[f"- `{f}`" for f in files_affected],
        "",
        "## Tests",
        tests_summary,
        "",
        "---",
        "_Generated by Verascope. All changes were reviewed and approved by a human before this PR was opened._",
    ]
    return "\n".join(lines)
